[package]
name = "aptos-crash"
version = "1.0.1"
authors = []

[addresses]
crash="_"

[dev-addresses]
crash="0xf048a4407f6b1282e70cde631705f17b4c68e79b99d59bf9aad8470b61d5b590"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
