[package]
name = "aptos-crash"
version = "1.0.0"
authors = []

[addresses]
crash="_"

[dev-addresses]
crash="0x2dc08391f7cc82cafa028d49854640676afc0e520d62f954bcc349c5d834f590"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
